apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RestrictedPSA
metadata:
  name: restricted-psa-enforcement
spec:
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
      - apiGroups: [""]
        kinds: ["Pod"]
    excludedNamespaces: ["kube-system", "gatekeeper-system", "kyverno"]
  parameters:
    exemptImages: []