// Products data to add after vendors
const mobileCategory = await tx.category.findFirst({ where: { slug: 'smartphone' } });
const laptopCategory = await tx.category.findFirst({ where: { slug: 'laptop-sub' } });
const fridgeCategory = await tx.category.findFirst({ where: { slug: 'refrigerator' } });
const toolsCategory = await tx.category.findFirst({ where: { slug: 'power-tools' } });

const products = await tx.product.createMany({
  data: [
    // Mobile phones
    {
      vendorId: vendors[0].id,
      categoryId: mobileCategory!.id,
      name: 'سامسونگ Galaxy S24 Ultra 256GB',
      slug: 'samsung-s24-ultra-256',
      description: 'گوشی پرچمدار سامسونگ با دوربین 200MP و قلم S Pen',
      sku: 'SAM-S24U-256',
      price: 58900000,
      compareAtPrice: 62000000,
      costPrice: 52000000,
      stock: 25,
      brand: 'Samsung',
      status: ProductStatus.ACTIVE,
      arType: ArType.HAND,
      rating: 4.9,
      reviewCount: 156,
      publishedAt: new Date(),
    },
    {
      vendorId: vendors[0].id,
      categoryId: mobileCategory!.id,
      name: 'اپل iPhone 15 Pro Max 256GB',
      slug: 'iphone-15-pro-max-256',
      description: 'آیفون 15 پرو مکس با تراشه A17 Pro و بدنه تیتانیوم',
      sku: 'APL-IP15PM-256',
      price: 74500000,
      compareAtPrice: 78000000,
      costPrice: 68000000,
      stock: 18,
      brand: 'Apple',
      status: ProductStatus.ACTIVE,
      arType: ArType.HAND,
      rating: 4.95,
      reviewCount: 203,
      publishedAt: new Date(),
    },
    {
      vendorId: vendors[1].id,
      categoryId: mobileCategory!.id,
      name: 'شیائومی Redmi Note 13 Pro 256GB',
      slug: 'xiaomi-note13-pro-256',
      description: 'گوشی میانرده با شارژ سریع 67 وات و دوربین 200MP',
      sku: 'XIA-RN13P-256',
      price: 12900000,
      costPrice: 11000000,
      stock: 85,
      brand: 'Xiaomi',
      status: ProductStatus.ACTIVE,
      rating: 4.6,
      reviewCount: 89,
      publishedAt: new Date(),
    },
    {
      vendorId: vendors[1].id,
      categoryId: mobileCategory!.id,
      name: 'هوآوی Nova 12 Pro',
      slug: 'huawei-nova12-pro',
      description: 'گوشی هوآوی با دوربین سلفی 60MP',
      sku: 'HUA-N12P',
      price: 18500000,
      costPrice: 16000000,
      stock: 42,
      brand: 'Huawei',
      status: ProductStatus.ACTIVE,
      rating: 4.4,
      reviewCount: 67,
      publishedAt: new Date(),
    },
    {
      vendorId: vendors[0].id,
      categoryId: mobileCategory!.id,
      name: 'نوکیا G42 5G',
      slug: 'nokia-g42-5g',
      description: 'گوشی نوکیا با پشتیبانی 5G و باتری 5000mAh',
      sku: 'NOK-G42-5G',
      price: 8900000,
      costPrice: 7500000,
      stock: 60,
      brand: 'Nokia',
      status: ProductStatus.ACTIVE,
      rating: 4.2,
      reviewCount: 45,
      publishedAt: new Date(),
    },

    // Laptops
    {
      vendorId: vendors[1].id,
      categoryId: laptopCategory!.id,
      name: 'لپتاپ ایسوس ROG Strix G16',
      slug: 'asus-rog-strix-g16',
      description: 'لپتاپ گیمینگ با RTX 4060 و Core i7-13650HX',
      sku: 'ASUS-ROG-G16',
      price: 68500000,
      compareAtPrice: 72000000,
      costPrice: 62000000,
      stock: 12,
      brand: 'ASUS',
      status: ProductStatus.ACTIVE,
      rating: 4.8,
      reviewCount: 34,
      publishedAt: new Date(),
    },
    {
      vendorId: vendors[1].id,
      categoryId: laptopCategory!.id,
      name: 'لپتاپ اپل MacBook Air M3',
      slug: 'macbook-air-m3',
      description: 'مک بوک ایر با تراشه M3 و نمایشگر Liquid Retina',
      sku: 'APL-MBA-M3',
      price: 52900000,
      costPrice: 48000000,
      stock: 15,
      brand: 'Apple',
      status: ProductStatus.ACTIVE,
      arType: ArType.WORLD,
      rating: 4.9,
      reviewCount: 78,
      publishedAt: new Date(),
    },
    {
      vendorId: vendors[0].id,
      categoryId: laptopCategory!.id,
      name: 'لپتاپ لنوو ThinkPad X1 Carbon',
      slug: 'lenovo-thinkpad-x1',
      description: 'لپتاپ بیزینس با Core i7 و صفحه 14 اینچ',
      sku: 'LEN-X1C-G11',
      price: 45800000,
      costPrice: 41000000,
      stock: 20,
      brand: 'Lenovo',
      status: ProductStatus.ACTIVE,
      rating: 4.7,
      reviewCount: 56,
      publishedAt: new Date(),
    },
    {
      vendorId: vendors[1].id,
      categoryId: laptopCategory!.id,
      name: 'لپتاپ HP Pavilion 15',
      slug: 'hp-pavilion-15',
      description: 'لپتاپ همه کاره با Core i5 و 16GB RAM',
      sku: 'HP-PAV-15',
      price: 28900000,
      costPrice: 25000000,
      stock: 35,
      brand: 'HP',
      status: ProductStatus.ACTIVE,
      rating: 4.5,
      reviewCount: 92,
      publishedAt: new Date(),
    },
    {
      vendorId: vendors[0].id,
      categoryId: laptopCategory!.id,
      name: 'لپتاپ دل Inspiron 16',
      slug: 'dell-inspiron-16',
      description: 'لپتاپ 16 اینچ با Ryzen 7 و صفحه FHD+',
      sku: 'DELL-INS-16',
      price: 32500000,
      costPrice: 28500000,
      stock: 28,
      brand: 'Dell',
      status: ProductStatus.ACTIVE,
      rating: 4.6,
      reviewCount: 71,
      publishedAt: new Date(),
    },

    // Appliances
    {
      vendorId: vendors[2].id,
      categoryId: fridgeCategory!.id,
      name: 'یخچال فریزر سامسونگ 30 فوت',
      slug: 'samsung-fridge-30ft',
      description: 'یخچال ساید بای ساید با دیسپنسر آب و یخ',
      sku: 'SAM-RF30-SBS',
      price: 89500000,
      costPrice: 78000000,
      stock: 8,
      brand: 'Samsung',
      status: ProductStatus.ACTIVE,
      arType: ArType.WORLD,
      rating: 4.7,
      reviewCount: 45,
      publishedAt: new Date(),
    },
    {
      vendorId: vendors[2].id,
      categoryId: fridgeCategory!.id,
      name: 'یخچال ال جی 28 فوت اینورتر',
      slug: 'lg-fridge-28ft-inverter',
      description: 'یخچال فریزر با کمپرسور اینورتر و فناوری Door Cooling',
      sku: 'LG-RF28-INV',
      price: 72900000,
      costPrice: 65000000,
      stock: 12,
      brand: 'LG',
      status: ProductStatus.ACTIVE,
      rating: 4.8,
      reviewCount: 67,
      publishedAt: new Date(),
    },
    {
      vendorId: vendors[2].id,
      categoryId: fridgeCategory!.id,
      name: 'یخچال اسنوا 20 فوت',
      slug: 'snowa-fridge-20ft',
      description: 'یخچال فریزر ایرانی با گارانتی 5 ساله',
      sku: 'SNO-RF20',
      price: 38900000,
      costPrice: 33000000,
      stock: 25,
      brand: 'Snowa',
      status: ProductStatus.ACTIVE,
      rating: 4.3,
      reviewCount: 89,
      publishedAt: new Date(),
    },

    // Tools
    {
      vendorId: vendors[1].id,
      categoryId: toolsCategory!.id,
      name: 'دریل شارژی بوش 18V',
      slug: 'bosch-drill-18v',
      description: 'دریل پیچ گوشتی شارژی با 2 باتری',
      sku: 'BOSCH-DRL-18V',
      price: 8900000,
      costPrice: 7500000,
      stock: 45,
      brand: 'Bosch',
      status: ProductStatus.ACTIVE,
      rating: 4.9,
      reviewCount: 234,
      publishedAt: new Date(),
    },
    {
      vendorId: vendors[1].id,
      categoryId: toolsCategory!.id,
      name: 'فرز آهنگری ماکیتا 2200W',
      slug: 'makita-grinder-2200w',
      description: 'فرز 230 میلیمتری صنعتی',
      sku: 'MAK-GRN-2200',
      price: 12500000,
      costPrice: 10500000,
      stock: 30,
      brand: 'Makita',
      status: ProductStatus.ACTIVE,
      rating: 4.8,
      reviewCount: 156,
      publishedAt: new Date(),
    },
  ],
});

console.log('✅ Created 20 products');
